apiVersion: skaffold/v4beta2
kind: Config
metadata:
  name: k-sapp
build:
  artifacts:
  - image: raileomor/k8sapp
manifests:
  rawYaml:
    - k8s/deployment.yaml
    - k8s/service.yaml
deploy:
  kubectl: {}