apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: k-sapp
build:
  artifacts:
    - image: raileomor/k8sapp
      docker:
        dockerfile: Dockerfile
manifests:
  rawYaml:
    - k8s/deployment.yaml
    - k8s/service.yaml
